apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eriuwspri-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eriuwspri-nodejs 
  name: eriuwspri-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: eriuwspri-nodejs 
